sudo: required
dist: trusty

# Enable C++ support
language: cpp

#Before compile
before_install:
  - sudo apt-get update
  - sudo apt-get install gcc-arm-linux-gnueabi
  - sudo apt-get install g++-arm-linux-gnueabi

# Build steps
script:
  - $CXX --version
  - echo $PWD
  - ls
  - cmake .
  - ls
  - make
