sudo: required
dist: trusty

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script:
  - $CXX --version
  - echo $PWD
  - ls
  - cmake .
  - ls
  - make
